### ISSUE TITLE
Parallelism

### ISSUE THREAD

**Issue by thetredev** [thetredev/gmakec#1]
Add explicit target dependencies to allow parallel builds. Something like:

```yaml
targets:
  - name: target-one
    ...
  
  - name: target-two
    ...
    depends:
      - target-one
```
