### ISSUE TITLE
CMake style compiler capabilities

### ISSUE THREAD

**Issue by thetredev** [thetredev/gmakec#10]
This is a huge one. CMake for example checks for `pthread`, `sys/types`, etc. capabilities/files. I'm not sure how to go about this. We could probably get inspiration from CMake modules, though: https://github.com/Kitware/CMake/tree/master/Modules

```yaml
compilers:
  - path: gcc
    checks:
      ...

# also applies to target-specific compilers:
targets:
  - compiler:
    path: gcc
    checks:
      ...
```

Also, it would be nice to let the developer disable those default checks:
```yaml
compilers:
  - path: gcc
    checks:
      default: false # defaults to true
```

Also also, the developer should be able to define their own checks:
```yaml
compilers:
  - path: gcc
    checks:
      default: true # for completeness
      custom:
        - name: My compiler check
          type: compile
          source: my/compiler/check.c
        - name: My filesystem check
          type: filesystem
          source: my/custom/header.h
```
Where `type: compile` would compile the file using `path`, and `type: filesystem` would check if the file is present on the system. If the check failed, an error message will be displayed prefixed by the value of `name`.

This structure is also easy to replicate in this project's source tree.

All of this would automatically resolve the `configure_files` TODO in https://github.com/thetredev/gmakec/blob/main/pkg/configure_file_definition.go#L16 (`// TODO: make this "cmake complete" and probably more fleixble...`), because we would have a giant variable store (like CMakes `CMAKE_` variables) to configure files from.
