### ISSUE TITLE
CMake style 'find' modules

### ISSUE THREAD

**Issue by thetredev** [thetredev/gmakec#12]
As an alternative to fixing issue #10, we could also simply provide lightweight CMake-like `Find*.cmake` modules for specific files/libraries. That way, we don't need to test the compiler for its capabilities and we can focus on finding files, basically. As a drawback, the developer will have to build the project and watch out for compiler error messages, should the compiler lack certain capabilities needed to build the project. I personally believe this is a better approach than the typical `configure` based one. We're nearing the end of 2023 after all. And yes, this is an excuse as I don't have any motivation to fix issue #10 right now. Not sure if we could additionally face legal issues as I have no idea if one can basically copy the intellectual property of Kitware, even if it's BSD-3 licensed (and I have no idea what that license *really* allows and what it doesn't). CMake's [`copyright.txt`](https://gitlab.kitware.com/cmake/cmake/raw/master/Copyright.txt) file only reads *you can modify CMake's source code if you want*, at least that's what I'm getting out of that. Not my cup of tea to be honest.

Even so, I'm thinking about something like this:
```yaml
compilers:
  - path: gcc
    find:
      - type: library
        names:
          - glew
      - type: library
        names:
          - glut
      - type: filesystem
        names:
          - python3
          - python3.11
          - python

# The path to the python executable would resolve the same way as $(realpath $(which python3)) would
# All of the above would also apply to targets:compiler of course
```

**Comment by thetredev** [comment]
The developer needs to be able to specifiy lookup paths themselves, just like you would with CMake. Something like:
```yaml
compilers:
  - path: gcc
    find:
      - type: library
        names:
          - glew
        paths:
          - /usr/lib
      - type: library
        names:
          - glut
      - type: filesystem
        names:
          - python3
          - python3.11
          - python
        paths:
          - /home/user/pyenv/my-python3-folder
```
These custom paths would then take precedence: custom paths &rarr; `PATH` &rarr; the ones this project defines, if any.
