### ISSUE TITLE
actions keyword

### ISSUE THREAD

**Issue by thetredev** [thetredev/gmakec#13]
Instead of only `command`s (for hooks), we could also create an `actions` keyword. Something like:
```yaml
actions:
  - id: python-version
    name: Define python version as compiler option
    shell: bash -c
    environment:
      - system:PATH
    command: python3 -V
    output:
      - define: SYSTEM_PYTHON_VERSION="<output>"

  - id: python-script
    name: Running python script
    shell: bash -c
    environment:
      - system:all # appends $(env) to command (not sure if needed when running in bash shell, but it's a showcase)
    command: python3 /some/python/script.py
    output: null # for completeness
  
  - id: multi-output
    name: Handle output in multiple ways
    shell: bash -c
    environment:
      - system:PATH # appends ${PATH} to command (not sure if needed when running in bash shell, but it's a showcase)
    command: hostname --ip-address
    output:
      - define: SYSTEM_HOSTNAME="<output>" # the developer has to make sure the output is exactly 1 line, gmakec doesn't care
      - file:
          type: text # or binary, fifo, socket:unix, socket:tcp, socket:udp
          path: /my/file/path.txt
          mode: append # or create
  
  - id: no-shell
    name: No shell command
    environment:
      - MY_VAR=MY_VALUE # commands without a shell don't have any environment variables set, so this will be the only one in this case
    command: /some/script/which/uses/MY_VAR.sh
    output: null

targets:
  - compiler:
    ...
    hooks:
      - step: preConfigure
        actions:
          - python-version
          - python-script
      - step: postBuild
        actions:
          - name: Some post build script # define completely new action here for this hook, no ID needed
            ...
```

This serves as a first idea. Gotta go to work now :D
