### ISSUE TITLE
Add target hooks

### ISSUE THREAD

**Issue by thetredev** [thetredev/gmakec#3]
Something like
```yaml
targets:
  - compiler:
    ....
    hooks:
      preConfigure: <command>
      postConfigure: <command>
      preBuild: <command>
      postBuild: <command>
```
