### ISSUE TITLE
Add target references

### ISSUE THREAD

**Issue by thetredev** [thetredev/gmakec#4]
Something like
```yaml
targets:
  - name: bla
    ...
    output: build/bla.o

  - name: use-bla-output
    ...
    sources:
      - ref:bla.output
```

**Comment by thetredev** [comment]
Fixed in https://github.com/thetredev/gmakec/commit/5de48fb04b073fbc98ce33da47aa34525f93002d

Changed the syntax to be more flexible:
```yaml
targets:
  - name: bla
    ...
    output: build/bla.o

  - name: use-bla-output
    ...
    sources:
      - bla:output
```
