### ISSUE TITLE
Target hooks will not work in all container environments

### ISSUE THREAD

**Issue by thetredev** [thetredev/gmakec#8]
Some container environments won't have a shell, e.g. `FROM scratch`. Thus, I think we should let the user decide which shell to use and how, something like:

```yaml
# sh
hooks:
  - shell: /bin/sh -c
    step: preConfigure
    command: echo "test"

# bash
hooks:
  - shell: /bin/bash -c
    step: preConfigure
    command: echo "test"

# none
hooks:
  - shell: none
    step: preConfigure
    command: /my/script.sh

# none (omit `shell` completely)
hooks:
  - step: preConfigure
    command: /my/script.sh
```
