### ISSUE TITLE
Platform independency

### ISSUE THREAD

**Issue by thetredev** [thetredev/gmakec#9]
Currently only Linux (and probably macOS, untested) is supported. We sould add something like:

```yaml
targets:
  - compiler:
    ...
    sources:
      - path: src/shared.c
      - path: src/linux.c
        platform: linux
      - path: src/macOS.c
        platform: macOS
      - path: src/windows.c
        platform: windows
        
```

Things to keep in mind:
- file line endings
- compiler support for platforms
- might as well add support for `targets:platform`
- probably more
